# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Open XDMoD Federated Module
email: ccr-xdmod-help@buffalo.edu
description: >
  An available Open XDMoD enhancement is Federated. This module provides the
  ability to have multiple disparate Open XDMoD installations replicate raw data
  to a core server to provide an overview of all systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://federated.xdmod.org" # the base hostname & protocol for your site
github_username: ubccr
github_url: https://github.com/ubccr/xdmod-federated
xdmod_module_name: Federated
latest_version: "8.0"
version_list:
    - "8.0"

defaults:
    -
        scope:
            path: "8.0"
            type: "pages"
        values:
            layout: "page"
            version: "8.0"
            menu_markdown: "8.0/menu.md"

# Build settings
markdown: kramdown
theme_subdir: "/xdmod-jekyll-theme"
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
